server:
        servlet:
                context-path: /javista
        port: 8080

spring:
        datasource:
                url: "jdbc:mysql://localhost:3306/JAVISTA"
                username: YOUR_DB_USERNAME
                password: YOUR_DB_PASSWORD
        jpa:
                hibernate:
                        ddl-auto: update
                show-sql: true
                properties:
                        hibernate:
                                format_sql: true
        mail:
                host: smtp.gmail.com
                port: 587
                username: YOUR_EMAIL
                password: YOUR_EMAIL_PASSWORD

        jackson:
                date-format: yyyy-MM-dd'T'HH:mm:ss
                time-zone: UTC

        servlet:
                multipart:
                        enabled: true
                        max-file-size: 10MB
                        max-request-size: 10MB

momo:
        momoApiUrl: "https://test-payment.momo.vn/v2/gateway/api/create"
        secretKey: YOUR_MOMO_SECRET_KEY
        accessKey: YOUR_MOMO_ACCESS_KEY
        returnUrl: "http://localhost:5173/payment"
        notifyUrl: "YOUR_NOTIFY_URL"
        partnerCode: YOUR_PARTNER_CODE

cloudinary:
        cloudName: YOUR_CLOUD_NAME
        apiKey: YOUR_API_KEY
        secretKey: YOUR_SECRET_KEY
        secure: true

jwt:
        signerKey: YOUR_JWT_SIGNER_KEY
        valid-duration: 7 # 7 days

esms:
        api-key: YOUR_ESMS_API_KEY
        secret-key: YOUR_ESMS_SECRET_KEY
        brand-name: "Baotrixemay"
        content: "Cam on quy khach da su dung dich vu cua chung toi. Chuc quy khach mot ngay tot lanh!"
        sms-type: 2
        url: "https://rest.esms.vn/MainService.svc/json/SendMultipleMessage_V4_post_json/"
        isUnicode: 0

origin:
        allowedPort: "http://localhost:5173"

app:
        default:
                admin:
                        username: "admin"
                        password: "admin"
                resident:
                        default-password: "123456"
                        changed-password: "12345678"
