server:
        servlet:
                context-path: /javista
        port: 8080

spring:
        datasource:
                url: "jdbc:mysql://localhost:3306/JAVISTA"
                username: root
                password: Admin@123
        jpa:
                hibernate:
                        ddl-auto: update
                show-sql: true
                properties:
                        hibernate:
                                format_sql: true
        mail:
                host: smtp.gmail.com
                port: 587
                username: buingocthuc1512@gmail.com
                password: tooy biet zawr reag

        jackson:
                date-format: yyyy-MM-dd'T'HH:mm:ss
                time-zone: UTC

        servlet:
                multipart:
                        enabled: true
                        max-file-size: 10MB
                        max-request-size: 10MB
momo:
        momoApiUrl: "https://test-payment.momo.vn/v2/gateway/api/create"
        secretKey: "K951B6PE1waDMi640xX08PD3vg6EkVlz"
        accessKey: "F8BBA842ECF85"
        returnUrl: "http://localhost:5173/payment"
        notifyUrl: " https://6545-125-235-239-167.ngrok-free.app/demoMoMo/bills/{{id}}/momo-callback"
        partnerCode: "MOMO"

cloudinary:
        cloudName: "daxuovzwp"
        apiKey: "723427193596933"
        secretKey: "NJufPii1Wh2R9SQsR3s71SSDbRc"
        secure: true
        defaultImage: "https://res.cloudinary.com/dloeqfbwm/image/upload/v1731292748/zity/assets/default_avt.jpg"

jwt:
        signerKey: "gKzxk9xGfL9xFiyxQ7ng+CLmK2POHD8Z3LkgqMDlx3AQcjZ6a3CcdGeLRSF2HJak"
        valid-duration: 7 # 7 days

esms:
        api-key: 072737DC8135CA37E90714B870974B
        secret-key: 4DE53EF785A0071024C284BF07AA5F
        brand-name: "Baotrixemay"
        content: "Cam on quy khach da su dung dich vu cua chung toi. Chuc quy khach mot ngay tot lanh!"
        sms-type: 2
        url: "https://rest.esms.vn/MainService.svc/json/SendMultipleMessage_V4_post_json/"
        isUnicode: 0

origin:
        allowedPort: "http://localhost:5173"

app:
        default:
                admin:
                        username: "admin"
                        password: "admin"
                resident:
                        default-password: "123456"
                        changed-password: "12345678"
