server:
  servlet:
    context-path: /javista
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/JAVISTA"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

